### ISSUE TITLE
Brainstorming for First Iteration

### ISSUE THREAD

**Issue by amadeusine** [umkc-cs-451-2020-spring/umscheduler#3]
Settled
- Not desktop app
- Not mobile app
- Web app

Ideas
- using Rust
    - Maybe Rocket.rs?
    - or something else
- using TypeScript / JavaScript
- Reach goal: WebAssembly

Roles
- [x] Front-end
- [x] API
- [x] Back-end (web)
- [x] Back-end (scheduling)
- [x] Databases (opt-in)

Additional Roles
- [x] Builds
    - [x] CI / CD
    - [x] Automated testing
- [x] Code reviews
- [x] Documentation

**Comment by thecookieraider** [comment]
Basically comfortable with any of the roles listed, but I'd like to focus heavily on CI/CD, automated testing, back-end (web) and back-end (scheduling). I can move around where needed of course.

**Comment by AliviaD** [comment]
I'd be interested in Front-end, back-end, and databases.  I would be willing to move around though.

**Comment by Yazdan24** [comment]
I will take the DB and documentation tasks

**Comment by amadeusine** [comment]
For the tasks of documentation, review and testing, we will need to work in cooperation for interacting components, and I hope that tools seen in #4 can help us in this regard.
